"""
Compliance report generation. PDF (filing/printing) and editable
.docx, per the problem statement's required export formats.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone

from docx import Document
from docx.shared import Pt, RGBColor
from weasyprint import HTML

from app.services.rule_engine import ComplianceResult

STATUS_META = {
    "pass": {"label": "PASS", "class": "pass", "hex": "2F6B4F"},
    "potential_non_compliance": {"label": "POTENTIAL NON-COMPLIANCE", "class": "fail", "hex": "B33A3A"},
    "review_required": {"label": "REVIEW REQUIRED", "class": "flag", "hex": "C08A2E"},
}

REPORT_CSS = """
@page { size: A4; margin: 2cm; }
body { font-family: 'IBM Plex Sans', Arial, sans-serif; color: #1B2A4A; }
h1 { font-size: 20pt; border-bottom: 3px solid #1B2A4A; padding-bottom: 8px; }
.meta { color: #55606E; font-size: 10pt; margin-bottom: 16px; }
.stamp { display: inline-block; padding: 6px 18px; border: 3px solid; border-radius: 4px;
         font-weight: bold; font-size: 14pt; letter-spacing: 1.5px; transform: rotate(-3deg); }
.pass { color: #2F6B4F; border-color: #2F6B4F; }
.fail { color: #B33A3A; border-color: #B33A3A; }
.flag { color: #C08A2E; border-color: #C08A2E; }
.company-note { margin-top: 14px; padding: 10px 14px; background: #FDF6E8; border-left: 3px solid #C08A2E; font-size: 10pt; }
table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 9.5pt; }
th, td { border: 1px solid #D8DEE4; padding: 6px 8px; text-align: left; vertical-align: top; }
th { background: #F5F7F8; }
.badge { font-family: 'IBM Plex Mono', monospace; font-size: 8.5pt; padding: 1px 6px; border-radius: 3px; }
.note { color: #55606E; font-family: 'IBM Plex Mono', monospace; font-size: 8.5pt; }
.rule-ref { color: #90979E; font-size: 8pt; }
"""


def _status_badge_html(status: str) -> str:
    meta = STATUS_META.get(status, STATUS_META["review_required"])
    return f'<span class="badge" style="background:#{meta["hex"]}22;color:#{meta["hex"]}">{meta["label"]}</span>'


def _report_html(
    product_name: str, scan_id: str, result: ComplianceResult, company_note: str | None = None
) -> str:
    meta = STATUS_META.get(result.overall_status, STATUS_META["review_required"])

    rows = ""
    for d in result.declarations:
        font_status = (
            f"{d.measured_height_mm}mm (min {d.min_required_height_mm}mm)"
            if d.measured_height_mm is not None
            else ("not measured" if d.min_required_height_mm else "n/a")
        )
        notes = "<br/>".join(f'<span class="note">{n}</span>' for n in d.notes)
        rows += f"""
        <tr>
          <td>{d.label}<br/><span class="rule-ref">{d.rule_source or ''} (v{d.rule_version or '-'})</span></td>
          <td>{_status_badge_html(d.status)}</td>
          <td>{font_status}</td>
          <td>{notes or '-'}</td>
        </tr>"""

    flags_html = ""
    if result.structural_flags:
        flags_html = "<h3>Flagged for manual review</h3><ul>"
        for f in result.structural_flags:
            flags_html += f'<li class="note">{f["description"]} (confidence: {f.get("confidence", "low")})</li>'
        flags_html += "</ul>"

    company_html = f'<div class="company-note">{company_note}</div>' if company_note else ""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    calibration_note = (
        "Font-size figures are barcode-calibrated estimates (assumes 1x GS1 magnification)."
        if result.calibrated
        else "No barcode detected -- font-size fields could not be measured this scan."
    )

    return f"""
    <html><head><style>{REPORT_CSS}</style></head><body>
      <h1>Legal Metrology Compliance Report</h1>
      <div class="meta">Product: {product_name} &nbsp;|&nbsp; Scan ID: {scan_id} &nbsp;|&nbsp; Generated: {generated_at}</div>
      <div class="stamp {meta['class']}">{meta['label']}</div>
      {company_html}
      <table>
        <thead><tr><th>Declaration</th><th>Status</th><th>Font size</th><th>Notes</th></tr></thead>
        <tbody>{rows}</tbody>
      </table>
      {flags_html}
      <p class="meta" style="margin-top:20px;">{calibration_note}</p>
      <p class="meta">
        Generated by automated rule-based screening under the Legal Metrology
        (Packaged Commodities) Rules, 2011. REVIEW REQUIRED and POTENTIAL
        NON-COMPLIANCE items require officer verification before enforcement action.
      </p>
    </body></html>
    """


def generate_pdf(product_name: str, scan_id: str, result: ComplianceResult, company_note: str | None = None) -> bytes:
    html = _report_html(product_name, scan_id, result, company_note)
    return HTML(string=html).write_pdf()


def generate_docx(product_name: str, scan_id: str, result: ComplianceResult, company_note: str | None = None) -> bytes:
    doc = Document()
    doc.add_heading("Legal Metrology Compliance Report", level=1)
    meta = doc.add_paragraph()
    meta.add_run(f"Product: {product_name}    Scan ID: {scan_id}    "
                  f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}").italic = True

    status_meta = STATUS_META.get(result.overall_status, STATUS_META["review_required"])
    verdict = doc.add_paragraph()
    run = verdict.add_run(status_meta["label"])
    run.bold = True
    run.font.size = Pt(16)
    hex_color = status_meta["hex"]
    run.font.color.rgb = RGBColor(int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16))

    if company_note:
        note_p = doc.add_paragraph()
        note_p.add_run(company_note).italic = True

    table = doc.add_table(rows=1, cols=4)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = "Declaration", "Status", "Font size", "Notes"
    for d in result.declarations:
        row = table.add_row().cells
        row[0].text = f"{d.label} ({d.rule_source or '-'}, v{d.rule_version or '-'})"
        row[1].text = STATUS_META.get(d.status, {}).get("label", d.status)
        row[2].text = (
            f"{d.measured_height_mm}mm (min {d.min_required_height_mm}mm)"
            if d.measured_height_mm is not None else "n/a"
        )
        row[3].text = "; ".join(d.notes) if d.notes else "-"

    if result.structural_flags:
        doc.add_heading("Flagged for manual review", level=2)
        for f in result.structural_flags:
            doc.add_paragraph(f'{f["description"]} (confidence: {f.get("confidence", "low")})', style="List Bullet")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
